AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  govuk-one-login adoption-application-config product-pages template version: v1.0.0
  Configuration parameters for the Product Pages application.

Parameters:
  Application:
    Description: The name of the application
    Type: String
    Default: "product-pages"
  Environment:
    Description: The environment type
    Type: String
    Default: local
    AllowedValues:
      - "local"
      - "dev"
      - "build"
      - "staging"
      - "integration"
      - "production"
  LocalName:
    Description: Unique name used for ephemeral environments
    Type: String
    Default: ""

Mappings:
  AdminTool:
    Environment:
      local: "https://admin.development.sign-in.service.gov.uk"
      dev: "https://admin.development.sign-in.service.gov.uk"
      build: "https://admin.build.sign-in.service.gov.uk"
      staging: "https://admin.staging.sign-in.service.gov.uk"
      integration: "https://admin.integration.sign-in.service.gov.uk"
      production: "https://admin.sign-in.service.gov.uk"
  GoogleAnalyticsDisabled:
    Environment:
      local: "false"
      dev: "false"
      build: "false"
      staging: "false"
      integration: "true"
      production: "true"
  GoogleAnalyticsGtmContainerId:
    Environment:
      local: "GTM-KD86CMZ"
      dev: "GTM-KD86CMZ"
      build: "GTM-KD86CMZ"
      staging: "GTM-KD86CMZ"
      integration: "GTM-KD86CMZ"
      production: "GTM-K4PBJH3"
  GoogleTagId:
    Environment:
      local: "GTM-PFTQ6G2"
      dev: "GTM-PFTQ6G2"
      build: "GTM-PFTQ6G2"
      staging: "GTM-PFTQ6G2"
      integration: "GTM-PFTQ6G2"
      production: "GTM-W38DXV2"
  GoogleSheetsEnabled:
    Environment:
      local: "true"
      dev: "true"
      build: "true"
      staging: "true"
      integration: "true"
      production: "true"
  JiraAuthUserName:
    Environment:
      local: "unknown"
      dev: "unknown"
      build: "unknown"
      staging: "unknown"
      integration: "unknown"
      production: "unknown"
  JiraIntegrationEnabled:
    Environment:
      local: "false"
      dev: "false"
      build: "false"
      staging: "false"
      integration: "false"
      production: "false"
  MailingListSheetDataRange:
    Environment:
      local: "unknown"
      dev: "unknown"
      build: "unknown"
      staging: "unknown"
      integration: "unknown"
      production: "unknown"
  MailingListSheetHeaderRange:
    Environment:
      local: "unknown"
      dev: "unknown"
      build: "unknown"
      staging: "unknown"
      integration: "unknown"
      production: "unknown"
  PrototypeAccessSheetDataRange:
    Environment:
      local: "unknown"
      dev: "unknown"
      build: "unknown"
      staging: "unknown"
      integration: "unknown"
      production: "unknown"
  PrototypeAccessSheetHeaderRange:
    Environment:
      local: "unknown"
      dev: "unknown"
      build: "unknown"
      staging: "unknown"
      integration: "unknown"
      production: "unknown"
  RegisterSheetDataRange:
    Environment:
      local: "unknown"
      dev: "unknown"
      build: "unknown"
      staging: "unknown"
      integration: "unknown"
      production: "unknown"
  RegisterSheetHeaderRange:
    Environment:
      local: "unknown"
      dev: "unknown"
      build: "unknown"
      staging: "unknown"
      integration: "unknown"
      production: "unknown"
  ShowTestBanner:
    Environment:
      local: "true"
      dev: "true"
      build: "true"
      staging: "true"
      integration: "true"
      production: "false"
  UniversalAnalyticsDisabled:
    Environment:
      local: "false"
      dev: "false"
      build: "false"
      staging: "false"
      integration: "false"
      production: "false"
  UniversalAnalyticsGtmContainerId:
    Environment:
      local: "GTM-TK92W68"
      dev: "GTM-TK92W68"
      build: "GTM-TK92W68"
      staging: "GTM-TK92W68"
      integration: "GTM-TK92W68"
      production: "GTM-TT5HDKV"
  UseStubJira:
    Environment:
      local: "true"
      dev: "true"
      build: "true"
      staging: "true"
      integration: "false"
      production: "false"
  UseStubServicenow:
    Environment:
      local: "true"
      dev: "true"
      build: "true"
      staging: "true"
      integration: "false"
      production: "false"
  UseStubSheets:
    Environment:
      local: "true"
      dev: "true"
      build: "true"
      staging: "true"
      integration: "false"
      production: "false"
  UseStubZendesk:
    Environment:
      local: "true"
      dev: "true"
      build: "true"
      staging: "true"
      integration: "false"
      production: "false"
  ZendeskApiUrl:
    Environment:
      local: "unknown"
      dev: "unknown"
      build: "unknown"
      staging: "unknown"
      integration: "unknown"
      production: "unknown"
  ZendeskTag:
    Environment:
      local: "unknown"
      dev: "unknown"
      build: "unknown"
      staging: "unknown"
      integration: "unknown"
      production: "unknown"
  ZendeskTagSSE:
    Environment:
      local: "unknown"
      dev: "unknown"
      build: "unknown"
      staging: "unknown"
      integration: "unknown"
      production: "unknown"

Conditions:
  IsLocal: !Equals [ !Ref Environment, "local" ]

Rules:
  LocalNameRequiredForLocalEnvironment:
    RuleCondition: !Equals [ !Ref Environment, "local" ]
    Assertions:
      - Assert: !Not [ !Equals [ !Ref LocalName, "" ] ]
        AssertDescription: >
          Must specify LocalName when Environment is "local"
  LocalNameEmptyForNotLocalEnvironment:
    RuleCondition: !Not [ !Equals [ !Ref Environment, "local" ] ]
    Assertions:
      - Assert: !Equals [ !Ref LocalName, "" ]
        AssertDescription: >
          Must not specify LocalName when Environment is not "local"
  ProtectIntegrationEnvironment:
    RuleCondition: !Equals [ !Ref AWS::AccountId, "663985455444" ]
    Assertions:
      - Assert: !Equals [ !Ref Environment, "integration" ]
        AssertDescription: >
          Only deploy "integration" parameters to the integration account
  ProtectProductionEnvironment:
    RuleCondition: !Equals [ !Ref AWS::AccountId, "389946456390" ]
    Assertions:
      - Assert: !Equals [ !Ref Environment, "production" ]
        AssertDescription: >
          Only deploy "production" parameters to the production account

Resources:
  AdminToolParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - "/"
        - - !Sub "/${Application}"
          - !If [ IsLocal, !Sub "${Environment}-${LocalName}", !Ref Environment ]
          - "frontend"
          - "admin-tool-url"
      Type: String
      Value: !FindInMap [ AdminTool, Environment, !Ref Environment ]
      Tags:
        "sse:component": "adoption-application-config"
        "sse:environment": !Ref Environment
        "sse:application": !Ref Application

  GoogleAnalyticsDisabledParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - "/"
        - - !Sub "/${Application}"
          - !If [ IsLocal, !Sub "${Environment}-${LocalName}", !Ref Environment ]
          - "frontend"
          - "google-analytics-4-disabled"
      Type: String
      Value: !FindInMap [ GoogleAnalyticsDisabled, Environment, !Ref Environment ]
      Tags:
        "sse:component": "adoption-application-config"
        "sse:environment": !Ref Environment
        "sse:application": !Ref Application

  GoogleAnalyticsGtmContainerIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - "/"
        - - !Sub "/${Application}"
          - !If [ IsLocal, !Sub "${Environment}-${LocalName}", !Ref Environment ]
          - "frontend"
          - "google-analytics-4-gtm-container-id"
      Type: String
      Value: !FindInMap [ GoogleAnalyticsGtmContainerId, Environment, !Ref Environment ]
      Tags:
        "sse:component": "adoption-application-config"
        "sse:environment": !Ref Environment
        "sse:application": !Ref Application

  GoogleTagIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - "/"
        - - !Sub "/${Application}"
          - !If [ IsLocal, !Sub "${Environment}-${LocalName}", !Ref Environment ]
          - "frontend"
          - "google-tag-id"
      Type: String
      Value: !FindInMap [ GoogleTagId, Environment, !Ref Environment ]
      Tags:
        "sse:component": "adoption-application-config"
        "sse:environment": !Ref Environment
        "sse:application": !Ref Application

  GoogleSheetsEnabledParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - "/"
        - - !Sub "/${Application}"
          - !If [ IsLocal, !Sub "${Environment}-${LocalName}", !Ref Environment ]
          - "frontend"
          - "google-sheets-integration-enabled"
      Type: String
      Value: !FindInMap [ GoogleSheetsEnabled, Environment, !Ref Environment ]
      Tags:
        "sse:component": "adoption-application-config"
        "sse:environment": !Ref Environment
        "sse:application": !Ref Application

  JiraAuthUserNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - "/"
        - - !Sub "/${Application}"
          - !If [ IsLocal, !Sub "${Environment}-${LocalName}", !Ref Environment ]
          - "frontend"
          - "jira-auth-user-name"
      Type: String
      Value: !FindInMap [ JiraAuthUserName, Environment, !Ref Environment ]
      Tags:
        "sse:component": "adoption-application-config"
        "sse:environment": !Ref Environment
        "sse:application": !Ref Application

  JiraIntegrationEnabledParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - "/"
        - - !Sub "/${Application}"
          - !If [ IsLocal, !Sub "${Environment}-${LocalName}", !Ref Environment ]
          - "frontend"
          - "jira-integration-enabled"
      Type: String
      Value: !FindInMap [ JiraIntegrationEnabled, Environment, !Ref Environment ]
      Tags:
        "sse:component": "adoption-application-config"
        "sse:environment": !Ref Environment
        "sse:application": !Ref Application

  MailingListSheetDataRangeParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - "/"
        - - !Sub "/${Application}"
          - !If [ IsLocal, !Sub "${Environment}-${LocalName}", !Ref Environment ]
          - "frontend"
          - "mailing-list-sheet-data-range"
      Type: String
      Value: !FindInMap [ MailingListSheetDataRange, Environment, !Ref Environment ]
      Tags:
        "sse:component": "adoption-application-config"
        "sse:environment": !Ref Environment
        "sse:application": !Ref Application

  MailingListSheetHeaderRangeParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - "/"
        - - !Sub "/${Application}"
          - !If [ IsLocal, !Sub "${Environment}-${LocalName}", !Ref Environment ]
          - "frontend"
          - "mailing-list-sheet-header-range"
      Type: String
      Value: !FindInMap [ MailingListSheetHeaderRange, Environment, !Ref Environment ]
      Tags:
        "sse:component": "adoption-application-config"
        "sse:environment": !Ref Environment
        "sse:application": !Ref Application

  PrototypeAccessSheetDataRangeParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - "/"
        - - !Sub "/${Application}"
          - !If [ IsLocal, !Sub "${Environment}-${LocalName}", !Ref Environment ]
          - "frontend"
          - "prototype-access-sheet-data-range"
      Type: String
      Value: !FindInMap [ PrototypeAccessSheetDataRange, Environment, !Ref Environment ]
      Tags:
        "sse:component": "adoption-application-config"
        "sse:environment": !Ref Environment
        "sse:application": !Ref Application

  PrototypeAccessSheetHeaderRangeParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - "/"
        - - !Sub "/${Application}"
          - !If [ IsLocal, !Sub "${Environment}-${LocalName}", !Ref Environment ]
          - "frontend"
          - "prototype-access-sheet-header-range"
      Type: String
      Value: !FindInMap [ PrototypeAccessSheetHeaderRange, Environment, !Ref Environment ]
      Tags:
        "sse:component": "adoption-application-config"
        "sse:environment": !Ref Environment
        "sse:application": !Ref Application

  RegisterSheetDataRangeParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - "/"
        - - !Sub "/${Application}"
          - !If [ IsLocal, !Sub "${Environment}-${LocalName}", !Ref Environment ]
          - "frontend"
          - "register-sheet-data-range"
      Type: String
      Value: !FindInMap [ RegisterSheetDataRange, Environment, !Ref Environment ]
      Tags:
        "sse:component": "adoption-application-config"
        "sse:environment": !Ref Environment
        "sse:application": !Ref Application

  RegisterSheetHeaderRangeParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - "/"
        - - !Sub "/${Application}"
          - !If [ IsLocal, !Sub "${Environment}-${LocalName}", !Ref Environment ]
          - "frontend"
          - "register-sheet-header-range"
      Type: String
      Value: !FindInMap [ RegisterSheetHeaderRange, Environment, !Ref Environment ]
      Tags:
        "sse:component": "adoption-application-config"
        "sse:environment": !Ref Environment
        "sse:application": !Ref Application

  ShowTestBannerParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - "/"
        - - !Sub "/${Application}"
          - !If [ IsLocal, !Sub "${Environment}-${LocalName}", !Ref Environment ]
          - "frontend"
          - "show-test-banner"
      Type: String
      Value: !FindInMap [ ShowTestBanner, Environment, !Ref Environment ]
      Tags:
        "sse:component": "adoption-application-config"
        "sse:environment": !Ref Environment
        "sse:application": !Ref Application

  UniversalAnalyticsDisabledParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - "/"
        - - !Sub "/${Application}"
          - !If [ IsLocal, !Sub "${Environment}-${LocalName}", !Ref Environment ]
          - "frontend"
          - "universal-analytics-disabled"
      Type: String
      Value: !FindInMap [ UniversalAnalyticsDisabled, Environment, !Ref Environment ]
      Tags:
        "sse:component": "adoption-application-config"
        "sse:environment": !Ref Environment
        "sse:application": !Ref Application

  UniversalAnalyticsGtmContainerIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - "/"
        - - !Sub "/${Application}"
          - !If [ IsLocal, !Sub "${Environment}-${LocalName}", !Ref Environment ]
          - "frontend"
          - "universal-analytics-gtm-container-id"
      Type: String
      Value: !FindInMap [ UniversalAnalyticsGtmContainerId, Environment, !Ref Environment ]
      Tags:
        "sse:component": "adoption-application-config"
        "sse:environment": !Ref Environment
        "sse:application": !Ref Application

  UseStubJiraParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - "/"
        - - !Sub "/${Application}"
          - !If [ IsLocal, !Sub "${Environment}-${LocalName}", !Ref Environment ]
          - "frontend"
          - "use-stub-jira"
      Type: String
      Value: !FindInMap [ UseStubJira, Environment, !Ref Environment ]
      Tags:
        "sse:component": "adoption-application-config"
        "sse:environment": !Ref Environment
        "sse:application": !Ref Application

  UseStubServicenowParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - "/"
        - - !Sub "/${Application}"
          - !If [ IsLocal, !Sub "${Environment}-${LocalName}", !Ref Environment ]
          - "frontend"
          - "use-stub-servicenow"
      Type: String
      Value: !FindInMap [ UseStubServicenow, Environment, !Ref Environment ]
      Tags:
        "sse:component": "adoption-application-config"
        "sse:environment": !Ref Environment
        "sse:application": !Ref Application

  UseStubSheetsParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - "/"
        - - !Sub "/${Application}"
          - !If [ IsLocal, !Sub "${Environment}-${LocalName}", !Ref Environment ]
          - "frontend"
          - "use-stub-sheets"
      Type: String
      Value: !FindInMap [ UseStubSheets, Environment, !Ref Environment ]
      Tags:
        "sse:component": "adoption-application-config"
        "sse:environment": !Ref Environment
        "sse:application": !Ref Application

  UseStubZendeskParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - "/"
        - - !Sub "/${Application}"
          - !If [ IsLocal, !Sub "${Environment}-${LocalName}", !Ref Environment ]
          - "frontend"
          - "use-stub-zendesk"
      Type: String
      Value: !FindInMap [ UseStubZendesk, Environment, !Ref Environment ]
      Tags:
        "sse:component": "adoption-application-config"
        "sse:environment": !Ref Environment
        "sse:application": !Ref Application

  ZendeskApiUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - "/"
        - - !Sub "/${Application}"
          - !If [ IsLocal, !Sub "${Environment}-${LocalName}", !Ref Environment ]
          - "frontend"
          - "zendesk-api-url"
      Type: String
      Value: !FindInMap [ ZendeskApiUrl, Environment, !Ref Environment ]
      Tags:
        "sse:component": "adoption-application-config"
        "sse:environment": !Ref Environment
        "sse:application": !Ref Application

  ZendeskTagParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - "/"
        - - !Sub "/${Application}"
          - !If [ IsLocal, !Sub "${Environment}-${LocalName}", !Ref Environment ]
          - "frontend"
          - "zendesk-tag"
      Type: String
      Value: !FindInMap [ ZendeskTag, Environment, !Ref Environment ]
      Tags:
        "sse:component": "adoption-application-config"
        "sse:environment": !Ref Environment
        "sse:application": !Ref Application

  ZendeskTagSSEParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - "/"
        - - !Sub "/${Application}"
          - !If [ IsLocal, !Sub "${Environment}-${LocalName}", !Ref Environment ]
          - "frontend"
          - "zendesk-tag-one-login-admin-tool"
      Type: String
      Value: !FindInMap [ ZendeskTagSSE, Environment, !Ref Environment ]
      Tags:
        "sse:component": "adoption-application-config"
        "sse:environment": !Ref Environment
        "sse:application": !Ref Application
