name: Build and deploy self-service experience configuration

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  deploy-development:
    name: Deploy (development)
    runs-on: ubuntu-latest
    environment: sse_development
    outputs:
      url: ${{ steps.deploy.outputs.pipeline-url }}
    steps:
      - name: Deploy (development)
        id: deploy-development
        uses: govuk-one-login/github-actions/secure-pipelines/deploy-application@a154a3241f59047aea80820a36c8e5cddb9d77ce # 8/05/2024
        timeout-minutes: 15
        with:
          aws-role-arn: ${{ vars.DEPLOYMENT_ROLE_ARN }}
          artifact-bucket-name: ${{ vars.ARTIFACT_SOURCE_BUCKET_NAME }}
          pipeline-name: ${{ vars.PIPELINE_NAME }}
          template: self-service/config.template.yml
