name: Build and deploy self-service experience configuration

on:
  push:
    branches:
      - main
    paths:
      - self-service/*

permissions: { }

defaults:
  run:
    shell: bash

env:
  STACK_NAME: onboarding-configuration-self-service-experience
  APPLICATION: self-service

jobs:
  deploy-development:
    name: Deploy (development)
    runs-on: ubuntu-latest
    environment: sse_development
    outputs:
      url: ${{ steps.deploy.outputs.pipeline-url }}
    steps:
      - name: Deploy (development)
        id: deploy-development
        uses: govuk-one-login/github-actions/secure-pipelines/deploy-application@94bfee8a40ab914626a7fb5bc459dd2c6a4ed435 # 5/03/2024
        timeout-minutes: 15
        with:
          aws-role-arn: ${{ env.DEPLOYMENT_ROLE_ARN }}
          artifact-bucket-name: ${{ env.ARTIFACT_SOURCE_BUCKET_NAME }}
          pipeline-name: ${{ env.PIPELINE_NAME }}
          template: $APPLICATION/config.template.yml
