name: Deploy self-service experience configuration

on:
  push:
    branches:
      - main
    paths:
      - self-service/*

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  deploy-development:
    name: Deploy Self-Service Experience Configuration (development)
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.pipeline-url }}
    steps:
      - name: Deploy (development)
        id: deploy-development
        uses: govuk-one-login/github-actions/secure-pipelines/deploy-application@a154a3241f59047aea80820a36c8e5cddb9d77ce # 8/05/2024
        timeout-minutes: 15
        with:
          aws-role-arn: ${{ secrets.SSE_DEV_DEPLOYMENT_ROLE_ARN }}
          artifact-bucket-name: ${{ secrets.SSE_DEV_ARTIFACT_SOURCE_BUCKET_NAME }}
          pipeline-name: ${{ secrets.SSE_DEV_PIPELINE_NAME }}
          template: self-service/config.template.yml

  deploy-production:
    name: Deploy Self-Service Experience Configuration (production)
    runs-on: ubuntu-latest
    needs: deploy-development
    outputs:
      url: ${{ steps.deploy.outputs.pipeline-url }}
    steps:
      - name: Deploy (production)
        id: deploy-production
        uses: govuk-one-login/github-actions/secure-pipelines/deploy-application@a154a3241f59047aea80820a36c8e5cddb9d77ce # 8/05/2024
        timeout-minutes: 15
        with:
          aws-role-arn: ${{ secrets.SSE_PROD_DEPLOYMENT_ROLE_ARN }}
          artifact-bucket-name: ${{ secrets.SSE_PROD_ARTIFACT_SOURCE_BUCKET_NAME }}
          pipeline-name: ${{ secrets.SSE_PROD_PIPELINE_NAME }}
          working-directory: self-service
          template: self-service/config.template.yml
