name: Deploy product pages configuration

on:
  push:
    branches:
      - main
    paths:
      - product-pages/*

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  deploy-development:
    name: Deploy Product Pages Configuration (development)
    runs-on: ubuntu-latest
    environment: pp_development
    outputs:
      url: ${{ steps.deploy.outputs.pipeline-url }}
    steps:
      - name: Deploy (development)
        id: deploy-development
        uses: govuk-one-login/github-actions/secure-pipelines/deploy-application@a154a3241f59047aea80820a36c8e5cddb9d77ce # 8/05/2024
        timeout-minutes: 15
        with:
          aws-role-arn: ${{ vars.DEPLOYMENT_ROLE_ARN }}
          artifact-bucket-name: ${{ vars.ARTIFACT_SOURCE_BUCKET_NAME }}
          pipeline-name: ${{ vars.PIPELINE_NAME }}
          template: product-pages/config.template.yml

# TODO Validate values before enabling full deployment.
#  deploy-production:
#    name: Deploy Product Pages Configuration (production)
#    runs-on: ubuntu-latest
#    needs: deploy-development
#    environment: pp_production
#    outputs:
#      url: ${{ steps.deploy.outputs.pipeline-url }}
#    steps:
#      - name: Deploy (production)
#        id: deploy-production
#        uses: govuk-one-login/github-actions/secure-pipelines/deploy-application@a154a3241f59047aea80820a36c8e5cddb9d77ce # 8/05/2024
#        timeout-minutes: 15
#        with:
#          aws-role-arn: ${{ vars.DEPLOYMENT_ROLE_ARN }}
#          artifact-bucket-name: ${{ vars.ARTIFACT_SOURCE_BUCKET_NAME }}
#          pipeline-name: ${{ vars.PIPELINE_NAME }}
#          template: product-pages/config.template.yml
